Feat/rest api and file provider
open-feature/flagd pull request #28
Opened 2022-06-08 02:32 UTC by toddbaert

This PR adds generation of an OpenFeature-compliant REST API from the OpenAPI spec including models, validation, and parsing. It also adds a `FilePathSync` implementation which watches a file for changes, does validation based on a json-schema, and caches the flag definitions until the file is changed.

The Chi framework was used since it has no dependencies, and is compatible with native go `net/http` handlers. 

To test:

- pull in the schema submodule with `git submodule update --init --recursive`
- `go mod download`
- run `make build` (which is now includes of `make generate`). The generated code is .gitignored.

Then, you can perform flag evaluations after running `./flagd start  --uri ./examples/provider_flags.json`

```
curl -X POST localhost:8080/flags/myBoolTest/resolve/boolean?default-value=true
// {"reason":"DEFAULT","value":true}

curl -X POST localhost:8080/flags/myStringTest/resolve/string?default-value=hi
// {"reason":"DEFAULT","value":"red"}

curl -X POST localhost:8080/flags/myNumericTest/resolve/number?default-value=123
// {"reason":"DEFAULT","value":1}

curl -X POST localhost:8080/flags/myObjectTest/resolve/object?default-value=foo,bar
// {"reason":"DEFAULT","value":{"color":"blue"}}
```
Closes: https://github.com/open-feature/flagd/issues/23
Closes: https://github.com/open-feature/flagd/issues/27

2022-06-08 07:57 UTC, AlexsJones commented
Hey great stuff, Can we talk this one through on a zoom call @toddbaert ?

2022-06-10 15:40 UTC, toddbaert commented on Makefile
> +generate:
new step generate is prereq for build

2022-06-10 15:45 UTC, toddbaert commented on pkg/eval/json_evaluator.go
> +package eval
The only current IEvaluator implementation. It maintains the flag state and knows how to intelligently parse it to evaluate flags as per OpenFeature spec.

2022-06-10 15:49 UTC, toddbaert commented on pkg/runtime/runtime.go
> +	go server.Serve(ev)
Server has handlers of some shape, which are run with the `.Serve()` method, which takes the `IEvaluation` for the handlers to call.

2022-06-10 16:00 UTC, toddbaert commented on pkg/sync/isync.go
> +	Notify(chan<- INotify)
Restricted this channel direction.

2022-06-10 16:16 UTC, toddbaert commented on pkg/eval/ievaluator.go
> +	SetState(state string) error
With this abstraction, it's actually possible to add IService impls that don't have well-defined transports as well... you could simply use GetState() to return the entire flag data, and only call that in whatever handler you implement.

2022-06-10 17:28 UTC, AlexsJones requested changes

2022-06-10 17:28 UTC, AlexsJones commented on Makefile
>  run:
We might also need to add generate here too?

2022-06-10 17:28 UTC, AlexsJones commented on cmd/start.go
> +	startCmd.Flags().StringVarP(&evaluator, "evaluator", "e", "json", "Set and evaluator e.g. json")
```suggestion
startCmd.Flags().StringVarP(&evaluator, "evaluator", "e", "json", "Set an evaluator e.g. json")
```

2022-06-10 17:34 UTC, toddbaert commented on Makefile
>  docker-build:
:100:

2022-06-10 17:34 UTC, toddbaert commented on pkg/runtime/runtime.go
> +	go server.Serve(provider)
Good catch. Go newbie issues.

2022-06-10 17:54 UTC, toddbaert commented on pkg/runtime/runtime.go
> +	go server.Serve(provider)
It seems like you commented on a sale commit here, possibly from the first PR before I rebased? I have added a context arg to resolve this comment, but you may want to take a look at this file again to make sure you saw the latest.

2022-06-10 18:26 UTC, merged