feat: Use OTel to export Prom Metrics
open-feature/flagd pull request #419
Opened 2023-02-19 22:05 UTC by thisthat

### Related Issues

In #186, there was a discussion about going with OpenTelemetry or a direct Prometheus implementation. 
The agreement was to have a scraping endpoint, i.e., `pull mode`,   and not support the `push` mode.
This PR wants to replace the existing direct Prometheus implementation with the vendor-agnostic OpenTelemetry one, maintaining the same feature set. 

### Notes

There are several benefits of using OpenTelemetry. The most prominent one is if we introduce Span supports in flagd, we could get out-of-the-box support for [exemplars](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#exemplars) to pin-point slow requests.

### Follow-up Tasks

- Introduce a flag to specify the OpenTelemetry collector URL ❓

2023-02-20 10:21 UTC, skyerus commented on pkg/service/connect_metrics.go
> +		log.Fatal("Missing Logger")
lowercase log messages to follow flagd's conventions

2023-02-21 16:52 UTC, beeme1mr commented
Hey @thisthat, thanks for the PR. This looks like a great improvement that will set us up to add trace support in the future.

2023-02-21 17:26 UTC, thisthat commented
Hey @beeme1mr, I am happy to provide a follow up PR with tracing support 😉

2023-02-21 20:48 UTC, toddbaert approved these changes
I'm not an OTel metrics expert, so I will approve but please consider my approval "low value" :sweat_smile:

2023-02-21 22:37 UTC, beeme1mr commented
I noticed that we haven't documented how to use Prometheus with Flagd. I created a follow up task to address that.
https://github.com/open-feature/flagd/issues/422

2023-02-22 21:15 UTC, beeme1mr commented
Hey @thisthat, I spent some time today digging into your PR and had some feedback. It looks like the request/response metric names and properties have changed.

Before:
`http_request_duration_seconds_bucket{code="200",handler="/schema.v1.Service/ResolveBoolean",method="POST",service="",le="0.005"} 6`

After:
`request_duration_seconds_bucket{http_method="POST",http_status_code="200",http_url="/schema.v1.Service/ResolveBoolean",otel_scope_name="openfeature/flagd",otel_scope_version="",service_name="openfeature/flagd",le="0"} 0`

If possible, it would be nice to keep the original names and values so that we maintain backwards compatibility. 

Next, it looks like the hitogram buckets have changed in the following ways:

Before:

- le="0.005"
- le="0.01"
- le="0.025"
- le="0.05"
- le="0.1"
- le="0.25"
- le="0.5"
- le="1"
- le="2.5"
- le="5"
- le="10"
- le="+Inf"

After:

- le="0"
- le="5"
- le="10"
- le="25"
- le="50"
- le="75"
- le="100"
- le="250"
- le="500"
- le="750"
- le="1000"
- le="2500"
- le="5000"
- le="7500"
- le="10000"
- le="+Inf"

I also noticed that the `otel_scope_version` is empty the `service_name` under the `target_info` gauge is "unknown_service".

2023-02-22 21:17 UTC, beeme1mr requested changes
Please maintain backwards compatibility.

2023-02-23 12:21 UTC, thisthat commented
Hey @beeme1mr thanks for looking into that! You are right, I have overlooked the bucket size and the subsystem declaration! I'll fix this! 

> I also noticed that the otel_scope_version is empty the service_name under the target_info gauge is "unknown_service".

This is because we don't configure any [OTel Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#resource-sdk) and the default values of the SDK are used. Here's the link to the SemConv: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service

if you don't mind, I will do that in a follow-up together with the tracing part since they go hand-in-hand

2023-02-23 20:45 UTC, beeme1mr approved these changes
Thanks @thisthat, looks good and works well.

FYI, the bucket property names have changed slightly but they seem to be more semantically correct based on the OTel spec.

2023-02-23 20:54 UTC, toddbaert commented
> Thanks @thisthat, looks good and works well.
> 
> FYI, the bucket property names have changed slightly but they seem to be more semantically correct based on the OTel spec.

I think we should through a `!` in the title and mention this, just so it stands out in the release notes.

2023-02-27 19:44 UTC, merged