docs: Move fractional evaluation pages to website
open-feature/flagd pull request #833
Opened 2023-08-14 00:31 UTC by agardnerIT

## This PR
- Moves fractional evaluation information to website

2023-08-16 12:53 UTC, beeme1mr requested changes

2023-08-21 16:09 UTC, craigpastro commented on web-docs/reference/fractional_evaluation.md
> +This works by hashing ([xxHash](https://cyan4973.github.io/xxHash/))
👋 I guess this line should be updated as #846 has been merged. https://github.com/open-feature/flagd/blob/c3c9e4e40aeae7e75b1b9ab13bb9a40264be84e5/docs/configuration/fractional_evaluation.md?plain=1#L17

2023-08-31 18:08 UTC, beeme1mr commented
@toddbaert @craigpastro, now that we've released the updated fractional evaluation logic, could you please confirm these docs are accurate?

2023-08-31 18:17 UTC, toddbaert commented
> @toddbaert @craigpastro, now that we've released the updated fractional evaluation logic, could you please confirm these docs are accurate?

They are not at all accurate because of the conflict. The "old" contents are being moved, and instead the "new" contents should be, I guess, but I'm not sure I fully understand the intent of the move itself.

2023-08-31 18:17 UTC, craigpastro commented
All examples and samples are still using the now deprecated `fractionalEvaluation` key. Should those be updated?

2023-08-31 18:19 UTC, toddbaert commented
> All examples and samples are still using the now deprecated `fractionalEvaluation` key. Should those be updated?

Ya, basically this "move" should be performed again with the updated content. I dont think any content needs to be changed.

2023-09-07 05:22 UTC, agardnerIT commented
Closing in favour of one larger, but easier to review PR: #825

2023-09-07 05:22 UTC, closed without merging